language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
before_install:
    - npm i -g npm@^2.0.0
before_script:
    - npm prune
script:
    - npm run testonce
